### ISSUE TITLE
How to build index for mouse using GENCODE vM24

### ISSUE THREAD

**Issue by zhanglab2008** [Mayrlab/scUTRquant#28]
Hi team, great work! Can you show me some example codes on how to build a custom index? My other analysis in the project used GENCODE vM24 and I want to run scUTRquant using the same annotation. Thank you in advance!
Zhang

**Comment by mfansler** [comment]
Hi @zhanglab2008, thanks for the interest!

Our pipeline for generating custom targets from GTF files is in [the `txcutr-db` repository](https://github.com/Mayrlab/txcutr-db). I still need to add some docs there for reuse, but the quick version would be:

```bash
git clone https://github.com/Mayrlab/txcutr-db.git
cd txcutr-db
snakemake --use-singularity --use-conda mus_musculus/gencode.vM24.annotation.pc.txcutr.w500.kdx
```

That command would generate a truncated index (KDX file), a GTF annotation, and a merge table (TSV) using GENCODE vM24. This would be with defaults of 500 nt truncation, 200 nt merge distance, and filtering GENCODE for only protein-coding transcripts with positively identified 3' ends (what we recommend). Note that the `txcutr` step is computationally intensive, e.g., in my runs I usually do 20 cores and 4GB memory per core, which takes about 30 mins to complete. Currently, that pipeline only supports Linux, since it uses Singularity (in addition to Conda and Snakemake). I can provide a Conda-only (i.e., Mac-compatible) version if you'd prefer - just ask.

Once the index is generated, those three files can be placed in a `extdata/targets/<your_target_name>` folder and then edit the `extdata/targets/targets.yaml` to have a new target entry. The target used in the mapping can then be edited *globally* in the `config.yaml`, specified in the dataset-specific `config.yaml`, or at the command line with `--config target="your_target_name"`.

Feel free to ask for any more clarification; any suggestions for usability improvements are also welcome!

**Comment by zhanglab2008** [comment]
Thanks very much! I will give it a try.

**Comment by zhanglab2008** [comment]
Hi Mervin,
I ran it but get an error:
```sh
Unexpected keyword container in rule definition (Snakefile, line 183).
```
Do I need to specify the path to my gtf file when I run the commmand?
```
snakemake --use-singularity --use-conda mus_musculus/gencode.vM24.annotation.pc.txcutr.w500.kdx
```
Thanks again!

**Comment by zhanglab2008** [comment]
I am using Ubuntu 20.04 by the way

**Comment by zhanglab2008** [comment]
I see. I may need to use the docker version (see line 183 in your snakemake file). 
```
   container:
        "docker://mfansler/scutr-quant:0.1.5"
```
Let me see if I can revise the codes.

**Comment by mfansler** [comment]
@zhanglab2008 likely, you need to upgrade the Snakemake version. There was an API change from `containers:` to `container` somewhere in the middle of Snakemake v5.x. Or editing it to `containers:` should also do the trick.

**Comment by zhanglab2008** [comment]
After I created a new conda environment and updated my snakemake, everything works like a charm now. Thanks Mervin! Good luck with the submission!

**Comment by mfansler** [comment]
@zhanglab2008 no, those are optional. I'd expect your target entry to be something like:

**extdata/targets/targets.yaml**
```
gencode_vM24_w500:
  path: "extdata/targets/gencode_vM24_w500/"
  genome: "mm10"
  gtf: "gencode.vM24.annotation.pc.txcutr.w500.gtf"
  kdx: "gencode.vM21.annotation.pc.txcutr.w500.kdx"
  merge_tsv: "gencode.vM21.annotation.pc.txcutr.w500.merge.tsv"
  tx_annots: null
  gene_annots: null
```

where `null` values indicate you don't have such annotations.

**Comment by zhanglab2008** [comment]
Got it. Thanks!!

**Comment by mfansler** [comment]
Closing this, as I believe it has been sufficiently resolved. Please reopen if there continues to be an issue.
